# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: seerr-secret
    namespace: media-downloaders
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:hj/dgVyRrC4a9AcshJPgSASyQAM5/tDCqlllmlDdRp35pyyUbQXC6LMRCRETW6X9gzvBDJ+2S5xKAEaUW29igg==,iv:nW/2BOM1lOfOD3OiYJUZZ9EcS6YnVGIcCWnbzQM6Boo=,tag:peDCRgJnUo6y8Ywrm47b5w==,type:str]
sops:
    age:
        - recipient: age1k8xaut2yz4ttudhtwxk0jf8ckrav2rugjup5vyqu3tyzp2lxhgxq93u2mf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid0VNWjhPZWpCUWN6elgx
            cXdCd0M2KzBMalp5L2ttMml2dXJCUEcxSkU0Cm16SzZjNVFGSVpZald6c2ZnQ0FY
            T3pBeUF3VjNJOWtiRzF2S3B5VCsxem8KLS0tIGs1aCtLK1lsU1pBRHhPbWsvbTlN
            MVFydnZMdDA4eFo1L3hEU3hUTHNOeEEKyQlKWtiz02JWm6A7QHrF+YzQV/0mytC7
            sSuRV5ZQs8gv4zsKH2GjOh1FgVALkud4FVUAAdW7ma5u5DTiDQW3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T17:10:56Z"
    mac: ENC[AES256_GCM,data:9bHvuRWt1zRVgTtoLu1C+WTtMuCd8/qZZcYUgljwxCUgZkjaoAOdNCI5cgvahoMej4cjodmnF9vJ43Hy0SggzN0omTl5l3oZgAK92KJ/L557vSRjkddNZ9LqQPu6GomtHQfU1qJgptQgguvOa1wDVZLq881wOeU60JxCNX1NwzQ=,iv:gqFWOedTAi/PNVHIUCAC7CpiDsw8G/IbXCPgcjjFPvM=,tag:gw9v579MTa3OlXfTKRTNsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
