# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: seerr-secret
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData: ENC[AES256_GCM,data:5eJZ8jAiWYSjhPdqJyL8CwtHKaXE2+FfRzGZnxvi7aaoyH9iqOjBeFB5NK1regv09UR2B0Ea3lbAG+LBQPvwLERw9DF9gSBp,iv:cBbIM4TCMbiqkIdH1u9Zz6OBdccJXoFDK5ViOxKvugE=,tag:rmpWzogDP1aozwdUpVuJpw==,type:str]
sops:
    age:
        - recipient: age1k8xaut2yz4ttudhtwxk0jf8ckrav2rugjup5vyqu3tyzp2lxhgxq93u2mf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid0VNWjhPZWpCUWN6elgx
            cXdCd0M2KzBMalp5L2ttMml2dXJCUEcxSkU0Cm16SzZjNVFGSVpZald6c2ZnQ0FY
            T3pBeUF3VjNJOWtiRzF2S3B5VCsxem8KLS0tIGs1aCtLK1lsU1pBRHhPbWsvbTlN
            MVFydnZMdDA4eFo1L3hEU3hUTHNOeEEKyQlKWtiz02JWm6A7QHrF+YzQV/0mytC7
            sSuRV5ZQs8gv4zsKH2GjOh1FgVALkud4FVUAAdW7ma5u5DTiDQW3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T17:08:50Z"
    mac: ENC[AES256_GCM,data:vsNst36tdtmJB6c5MGDyEr3dyIQcr3nQJqK1V2cimEbnKzdNYhqEX1S9JbKoISMrlbSITxHU5VAn8sLG6UzkaNKKgwvG8fmxK63YQANWs21u+ou9KIft6EMcUQ4tT6AHMeA88vA8ZYSxOUqZsqUMxzLaLzhNguaYaXr81wI6Mds=,iv:4Pi8lQDD9BaqOAxwrLvNEsHAus/SbP7ecJtgpvS+pfM=,tag:gpYslDgDstcTBcoMIw1sZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
