---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./kubernetes-dashboard.yaml
  - ./rook-release.yaml
