---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ./helmrelease.yaml
  - ./gitlab-runner-secret.sops.yaml
  - ./buildkit.yaml
  - ./r2cache-externalsecrets.yaml
