---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: r2cache-externalsecrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitlab-runner-r2cache
    creationPolicy: Owner
  dataFrom:
    - extract:
        # secretkey, accesskey
        key: gitlab-runner-r2cache
