---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./harbor-registry-cluster-external-secret.yaml
  - ./gitlab-runner/ks.yaml
  - ./gitlab-runner-internal/ks.yaml
  - ./gitea/ks.yaml
  # - ./renovate/ks.yaml
  - ./harbor/ks.yaml
  # - ./kafka/ks.yaml
