# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: dev-zitadel-secret
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ZwuUWfdgZbx1dtsGJAc=,iv:ql7syZ02BQ/A1E/gpylEFsiu5iykRWqkeUPo2ysirUQ=,tag:HYN9DqBfc9Tux2Nkhw0nCw==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:M4NzxQraeKFg8Wk=,iv:3DAt5Hb4o0YXb7/VlLTlPw0ogMt9V/yipn2M5DLkhIs=,tag:tFOsm8qOzA54QPtJ54ma0g==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:5EBgC6setnJ+7BdIaZj8jLbnGaCYWc24cgSONV5vpA==,iv:F+kXQKjuk1ggBqi/Nwg2I6Yzew6I1sROqp3dygWS6tQ=,tag:EpmU77gzdCw0mUT5nOgw9w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:AhV9oaY3SQ==,iv:v/y1KcyXF5j4iY57v5WqNUwQFMWkf7cNBWXux3JXJyo=,tag:jrk56dXwf93pMPr0C+EkVA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:URkm5kOdoGmbjlce,iv:CBPhlEh62+CqvoO/rcJdrlaVwvd+xvYOk/CMwu6TXfQ=,tag:qx481ygLhUWNhKCtOopQHA==,type:str]
    POSTGRES_ADMIN_USER: ENC[AES256_GCM,data:Av0dYT8chxE=,iv:vCQYUATBrDsCpk+VTAAdDQuxF/xLTO8kUXKevYY1p9U=,tag:TcKgVmRl+r7qmVLVmGMF4w==,type:str]
    POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:kUV8LZEsbb2tYePm,iv:H93cxQMrHfVB4VTg3sut4tBPn/rO92tfYr07Z4rdC4s=,tag:tyWasSADcjg7/o/n/CbEIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k8xaut2yz4ttudhtwxk0jf8ckrav2rugjup5vyqu3tyzp2lxhgxq93u2mf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid0VNWjhPZWpCUWN6elgx
            cXdCd0M2KzBMalp5L2ttMml2dXJCUEcxSkU0Cm16SzZjNVFGSVpZald6c2ZnQ0FY
            T3pBeUF3VjNJOWtiRzF2S3B5VCsxem8KLS0tIGs1aCtLK1lsU1pBRHhPbWsvbTlN
            MVFydnZMdDA4eFo1L3hEU3hUTHNOeEEKyQlKWtiz02JWm6A7QHrF+YzQV/0mytC7
            sSuRV5ZQs8gv4zsKH2GjOh1FgVALkud4FVUAAdW7ma5u5DTiDQW3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T03:21:29Z"
    mac: ENC[AES256_GCM,data:mVpEr7uM/KQITWNLiCwMHRxWDbh1lDxu3broN54CwVpmCeFGS6fVx6scrOEJukBzQ+w6TJLSXL+o+W8oyPX/nOurqubYds51Mgp4x5218UnVdiokwkTi3KWqVc9iJUKNOVab7mWod6l/8gozxvMDjXLotYKbyjUgbYTZToGExpg=,iv:oxmcuptAxU11YzhtlM0QyZqKZuFriw8j6tq20aIAApI=,tag:uF4b1JmiVCxTgYxpoQgNdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
