apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ycQ+0ksHVAs=,iv:5Z1qNBQ7TO6qEvBDgXD5tUYxHpL4lzKo6+MMtXR2rew=,tag:oWYpXhyFOCJ9ARE2HrCdhg==,type:str]
    SECRET_USERNAME: ENC[AES256_GCM,data:UZ2vDg==,iv:NzXLfuNPQhBBUGeOm6XmL55MkVx/uwJq4Xr0UZjpO6Q=,tag:nE9/wgZlI15K9Nj2S9fA4A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mNdh9CTFQ+W8ndjgKnQI3sIx,iv:yNHkynRLefPV4Mt6zvVZzgtWtbVMEOQB8WhrxCvnF3o=,tag:4qrz77IyRkIpWheaDs7yOg==,type:str]
    SECRET_NFS_IP: ENC[AES256_GCM,data:LIfWazD4bZh7wVLq,iv:exCm7qwPoOJXr/Hv+gASSBvVWR6KByAJ7N3gY1RILHg=,tag:35n3MOC/1lG5mzNAF1PmoQ==,type:str]
    SECRET_HOME_NETWORK_CIDR: ENC[AES256_GCM,data:wIrp1rmPuKxY1G13V8c=,iv:ZN5QNHZ6edbGl45V1kOKpG/c6zwr55HXQT/psAoQD78=,tag:jY990MmlWZbmOYYv1T7SWQ==,type:str]
    SECRET_SHORT_DOMAIN: ENC[AES256_GCM,data:4ADGIxM=,iv:FVmHBZ8ijxXJ4gK2J4S1t5n0hj99nYGC3OXfjoP3K6c=,tag:kLrzwmKcaVuS37xt6rERig==,type:str]
    SECRET_EXT_DOMAIN: ENC[AES256_GCM,data:a/aQtZvkNQ==,iv:ZFOC+kE1ENzvm4VLj3kNFr/Jng1hn1qF9jeTB19GqEw=,tag:mrjj2P7DzFDb0nyACxvnDA==,type:str]
    SECRET_EXT_INFRA_DOMAIN: ENC[AES256_GCM,data:UFwYR+rUNuxRi32M7X0sdmk=,iv:2kKKu7qxPSCId/48kA4SNRvQpweFPo1WTmbMCwA0wdU=,tag:QyEsAidhUgseo7eBpEUTKA==,type:str]
    SECRET_REGISTRY_DOMAIN: ENC[AES256_GCM,data:NF8QOCcNg5o=,iv:4n7t2ennP+LusbjyBoIpM7em93yrTumrJ99laP6++Ck=,tag:gQ34AthP/9yQmxHvihqM+g==,type:str]
    SECRET_INTERNAL_DEPLOY_DOMAIN: ENC[AES256_GCM,data:IMbeIZOa07s=,iv:PPef+RmUOtfd3uj7VHO6sfpf/fCYitlt2K5JXAOcPJo=,tag:5X8KZ1R0LxCUsolS873gOw==,type:str]
    SECRET_APPSPLATFORM_PRD_DOMAIN: ENC[AES256_GCM,data:20Gco7Vk2W2ECxsOGQ==,iv:OUOxv5114WZsv3NAmNWU1qoGZVsIoclh5o/FB0KBJhs=,tag:S4hwYZiNzd+m20oiYO4Peg==,type:str]
    SECRET_WEATHERJP_DOMAIN: ENC[AES256_GCM,data:KW0IIjDHNLGRcVpzag==,iv:MpWgtR/6TEibaHCWBnHL5bvWD3tR0b8K1fBchqzf8mY=,tag:bGSFxJQTv70IpWmLuM6L3w==,type:str]
    SECRET_CLOUDFLARED_TUNNEL_ID: ENC[AES256_GCM,data:N8EJ6Qi8iO9is/NqMerNxfHDzEg3lHSPQxN9rhMlvhEeD+nT,iv:jTRZKrmlUryPTiqQ7xvRDSzqlGd8EK7z0SkYZ+HH97U=,tag:BBg4LVX4HwE78gxdJw584Q==,type:str]
    SECRET_GITEA_SSH_IP: ENC[AES256_GCM,data:hGHqyeuqFyL0B5WcvQ==,iv:jpOtGjwRiNdQcclu7vsb/UaV092yDWF0PeOLjQiDAEY=,tag:Am8VK/HnoEBFpTEl/P6iog==,type:str]
    SECRET_LB_SMTP_IP: ENC[AES256_GCM,data:4eX/0qaF5gbGDFODig==,iv:FZG/VuLQT6zt2vq/uK/gB414oH4aX2ffb5jmrEVifB4=,tag:aGOdY5GD2MZoVfU/KcCPww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k8xaut2yz4ttudhtwxk0jf8ckrav2rugjup5vyqu3tyzp2lxhgxq93u2mf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURmd5Z05PcnJKTkhpZzg4
            YkQvdHJrT05PS1IvWmxiSG1vYlNsdE8wWkZNClRITTBnMzcycmE5T3RYckNZcWRQ
            MHlCNUVvOU96ZkpoekR5YlRLaXNMT2MKLS0tIDBDSzZTMG1Zc2dXMm1kbWRuOWxr
            UmVmeVdicEg0aUtwZnVuRXB0cjF2ZDAKm8uvXNynXO6W6oDYuYOzFB3LJg2EI/EU
            BZRhBudO0fjvBT2e9/xmr6GPO1H9hS6qmE/dLh0/p7C6RYp2jb6iGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T00:51:38Z"
    mac: ENC[AES256_GCM,data:+EqD9BKkL7yzIW1bcZQmDWhk2deqHSRC5O8utPm4ffMkIohAZoP/nkWP2OqQUlx65hLY7PckUfj+A9RB7i3g1JOkNQCSf99JRgmvl0tnvHf4sohFWKgmeztGIGsTvqR3yS99fWOMMwbWgrvTWY1/Rtlsbe299OnqhDubCNCrgL0=,iv:Qdi488XqJnMSPCxU2Y7mwd5SNYECsXVO3e5SlZ7qOrw=,tag:ppWPFIB1oAzhj5aK15YKcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
