---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./helmrelease.yaml
  - ./cloudflared-credentials.sops.yaml
configMapGenerator:
  - name: cloudflared-config
    files:
      - ./cloudflared-config.yaml
generatorOptions:
  disableNameSuffixHash: true
